name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request: # required to have reports on PRs
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        env:
          CODSPEED_LOG: trace
        with:
          mode: simulation
          run: Rscript -e 'cod::test_file("tests/bench/c.R")'
